#Bien, hasta aquí no hay nada nuevo. Creamos el job, Mi primer job, y definimos el SO en el que debe correr para las Github actions. Ahora vamos a añadir un paso o step en donde realizaremos una impresión simple por pantalla.
name: Mi primer intento
on:
    push:
        branches: [ master ] #cuando se haga el push en master
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }} #estamos definiendo que el job tendrá justamente un output de nombre salida, que para el paso Imprimir (al que hemos agregado el id imprimir) se llamará internamente respuesta.
    steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola mundo
      run: echo "::set-output name=respuesta::${MI_VARIABLE}" #es definir la variable de salida interna respuesta con el valor de MI_VARIABLE, es decir, "Hola mundo".
  Mi-segundo-job:
    needs: Mi-primer-job #depende del anterior, si no se define se realizarán los jobs paralelamente
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.Mi-primer-job.outputs.salida}} #Va a traer la info de salida de mi primer job
